---
title: "Covid"
author: "Federico"
date: '2022-07-13'
output: html_document
---

```{r}
#importiamo il csv che ci servirà per l'analisi della patologia covid19
covid <- read.csv("staticovid19.csv")
```

```{r}
#importiamo tutte le librerie
library(tidyverse)
library(ggplot2)
library(dplyr)
library(plotrix)

```

```{r}
#PULIZIA DATASET

#rimuovo colonne che non mi interessano del dataset covid
covid <- subset( covid, select = -c(New.cases, New.deaths, New.recovered,Deaths...100.Recovered,Confirmed.last.week,X1.week.change, X1.week...increase ) )

#rinomino le colonne che mi interessano del dataset covid
names(covid)[names(covid)=="Country.Region"] <- "Stato"
names(covid)[names(covid)=="Confirmed"] <- "CasiAccertati"
names(covid)[names(covid)=="Deaths"] <- "Morti"
names(covid)[names(covid)=="Recovered"] <- "Ricoverati"
names(covid)[names(covid)=="Active"] <- "Positivi"
names(covid)[names(covid)=="WHO.Region"] <- "Continente"
names(covid)[names(covid)=="Deaths...100.Cases"] <- "Decessi su 100 casi"
names(covid)[names(covid)=="Recovered...100.Cases"] <- "Ricoverati su 100 casi"


#rinomino i continenti, africa lo tengo cosi

covid[covid$Continente == "Europe","Continente"] <- "Europa"
covid[covid$Continente == "Americas","Continente"] <- "America"
covid[covid$Continente == "Eastern Mediterranean","Continente"] <- "Asia"
covid[covid$Continente == "South-East Asia" ,"Continente"] <- "Asia"
covid[covid$Continente == "Western Pacific","Continente"] <- "Oceania"

```

```{r}
#Quale continente ha il maggior numero di positivi attualmente?

covid %>% 
  ggplot(aes(Continente,Positivi), ylim= c(0,4000000)) +
  geom_bar(stat="identity", fill="lightblue") +
  coord_flip() +
  labs(title="Casi positivi per continente", x="Continente", y="Numero di positivi") +
   theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5, colour = "blue", size = 15),
          axis.title.x = element_text(size= 12, color = 'blue'),
          axis.title.y = element_text(size = 12, color = 'blue'))

#seleziono i cinque stati con il maggior numero di positivi.
covidMaggioriPositivi <- covid %>%
                  arrange(desc(Positivi)) %>%
                  select(Stato,Positivi,CasiAccertati) %>%
                  head(5)

#dei 5 stati con maggior numero di positivi, guardo la percentuale relativa
#in seguito sono riportate le percentuali dei positivi sui casi accertati totali dei relativi stati
ggplot(data = covidMaggioriPositivi, aes(Stato, (Positivi/CasiAccertati))) +
geom_point(size = 3, color = "lightblue")

```


```{r}
#quale continente ha il maggior numero di ricoverati?
#scala da 0 a 4 milioni

covid %>% 
  ggplot(aes(Continente,Ricoverati)) +
  geom_bar(stat="identity", fill="lightgreen") +
  coord_flip() +
  labs(title="Ricoverati per ogni continente",x="Continenti",y="Numero di Ricoverati") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size=14), 
        axis.title.x = element_text(size= 12, color = 'black'),
        axis.title.y = element_text(size = 12, color = 'black'))
```

```{r}
#Quale stato ha il maggior numero di ricoverati?

StatiConPiuRicoverati <- covid %>%
                          arrange(-Ricoverati) %>%
                          select(Stato,Ricoverati) %>%
                          head(10)

#tramite il grafico si notano che i tre picchi sono proprio su US,Brasile e India
ggplot(data = StatiConPiuRicoverati, aes(Stato,Ricoverati)) +
  geom_bar(stat="identity", fill="lightgreen") +
  labs(title="Ricoverati per stato", x="Stato", y="Persone ricoverate") +
   theme_bw() +
    theme(plot.title = element_text(hjust = 0.5, size = 15, colour = "red"),
          axis.text.x = element_text(angle = 90,size= 10, color = 'black'))

```

```{r}
#qual'è il continente che mostra il numero di ricoveri maggiore su 100 casi (campione)?
covid %>% 
  ggplot(aes(Continente,`Ricoverati su 100 casi`)) +
  geom_bar(stat="identity", fill="lightgreen") +
  labs(title="Ricoverati su 100 casi per ogni continente",
       x="Continenti",
       y="Ricoverati su 100 casi") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 15),
        axis.title.x = element_text(size= 12, color = 'black'),
        axis.title.y = element_text(size = 12, color = 'black'))
```

```{r}
#Qual'è lo stato che ha maggior numero di decessi?
#seleziono i tre stati dell'Europa con il maggior numero di deceduti in Europa.
#ho inserito maggiori di mille perchè altrimenti molti stati approssimavano a 0
CovidDeceduti <- covid %>%
                  filter(Continente == "America" & Morti > 1000) %>%
                  select(Stato,Morti)

#dal grafico si percepisce come l'america ha il maggior numero di deceduti
  ggplot(data = CovidDeceduti, aes(Stato,Morti)) +
  geom_bar(stat="identity",position=position_dodge(), fill="orange") +
  labs(title="Deceduti per stato", x="Stato", y="Numero di Morti avvenute") +
   theme_replace() +
    theme(plot.title = element_text(hjust = 0.5, size = 15, colour = "red"),
          axis.text.x = element_text(angle = 90,size= 10, color = 'black'))

```

```{r}
#quale sono i cinque stati che mostrano il numero di decessi maggiore su 100 casi?

StatiConPiuDecessi100casi <- covid %>%
                            arrange(-`Decessi su 100 casi`) %>%
                            select(Stato,`Decessi su 100 casi`) %>%
                            head(5)

#tramite il grafico si notano che i tre picchi sono proprio su US,Brasile e India
ggplot(data = StatiConPiuDecessi100casi, aes(Stato,`Decessi su 100 casi`), ylim = c(0,40)) +
  geom_bar(stat="identity", fill="orange") +
  labs(title="Decessi per stato", x="Stato", y="Numero di decessi") +
   theme_bw() +
    theme(plot.title = element_text(hjust = 0.5, size = 15),
          axis.text.x = element_text(size= 10))


```


```{r}
#In quale stato non è stato contratto il covid o eventualmente, non ha avuto ripercussioni gravi?
#ipotizziamo che per non avere ripercussioni gravi, i casi non superano i cento

covidNonGrave <- (covid %>%
                  filter(CasiAccertati <= 100) %>%
                  select(Stato,CasiAccertati))

ggplot(data = covidNonGrave, aes(Stato, CasiAccertati)) +
  labs(title = "Stati dove il covid non ha colpito eccessivamente") +
  geom_point(size = 2, color = "red") +
  theme_get() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, colour = "red"),
          axis.text.x = element_text(angle = 90,size= 10))
  

```

```{r}
#come è la situazione in italia? qual'è la percentuale di positivi, di morti e di ricoverati?

#prendo i dati relativi allo stato italiano
covid %>%
  filter (Continente == "Europa" & Stato == "Italy")

#creo due array per formare il mio diagramma a torta
#siccome mi serve percentuale divido tutti i dati (positivi,morti,ricoverati) per i casi accertati.
Percentuali <- c(12581/246286, 35112/246286, 198593/246286)
StatoSalute <- c("Positivi", "Deceduti", "Ricoverati")
pie(Percentuali, labels = StatoSalute, main = "Statische casi accertati covid19 Italia")
  
```

```{r}
#quale continente a ricoveri più alti su 100 casi?
covid %>% 
  ggplot(aes(Continente,`Ricoveri su 100 casi`)) +
  geom_bar(stat="identity", fill="#78D0E2") +
  labs(title="Ricoveri su 100 casi per ogni continente",
       x="Continenti",
       y="Ricoveri su 100 casi") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size=16),
        axis.text.x = element_text(size= 10, color = 'black'),
        axis.text.y = element_text(size = 10, color = 'black'),
        axis.title.x = element_text(size= 13, color = 'black'),
        axis.title.y = element_text(size = 13, color = 'black'))
```

